### ISSUE TITLE
Error response from daemon: invalid subinterface vlan name en0, example formatting is eth0.10

### ISSUE THREAD

**Issue by 0xwang-coder** [alextanhongpin/full-stack-microservice#2]
OS: mac 10.13.6
docker: 18.09.2
when I excuting the command:
`docker network create -d macvlan  --subnet=192.168.2.0/24 --gateway=192.168.2.2 -o parent=en0 mynet`. The error 'Error response from daemon: invalid subinterface vlan name en0, example formatting is eth0.10' was shown. I searched all web, but there were 2 issues relationed to this error. 
Had you soled this problem?

**Comment by piyushchauhan2011** [comment]
Are we building a spaceship soon to deploy to mars with this architecture? @alextanhongpin

**Comment by 0xwang-coder** [comment]
> Are we building a spaceship soon to deploy to mars with this architecture? @alextanhongpin

I dont know why I had this issue below this project，there is a long time. Maybe it's my fault. Just clost it.
